
POST localhost:8080/api/v1/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NVUEVSVklTT1IiXSwiaWQiOjcsImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoidGVzdCIsInN1YiI6InRlc3QiLCJpYXQiOjE3MzM0MzI3MjUsImV4cCI6MTczMzU3NjcyNX0.eKZ7Cl_JimCmx8N5s8t3fhQwj4XKdreWUjRuoi7rbQyryYSvHrSWsQMzvO8wShjwulEg5IpuLIxt4dYgpQewW7rtvq7Lbt1Y5pdqKh3zu9AwlC8j3b0dVKAHVswnC02VqTIVthDhLodWA-D1PrZOZf2Wc0tJVfj3MdKija6Nby4z2I8ZYubGOsVBWzS7TU2O7Uhc7trXl6_ziWyLYoYqQ6w8B4sOuhkE_QnrkH9DZGNqQ5aYG3-Ft3XntYxcQfCJKlW8E5M1SQ2t14OiUE3JfwQrqynLl9mdmKoX8gvBcECtJSjI5hOE90fC568Bv6MI-coeDeQXKZcvdO-6ewHwNA


{
  "id": 0,
  "login": "user",
  "email": "user@a.ru",
  "pass": "user",
  "role": "USER"
}

###
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
"id": 0,
"login": "user",
"email": "user@a.ru",
"pass": "user",
"role": "USER"
}


###
POST localhost:8084/api/v1/auth/login
Content-Type: application/json

{
  "id": 0,
  "login": "test",
  "email": "email@a.ru",
  "pass": "test",
  "role": "admin"
}



###
GET localhost:8080/api/v1/content/movie/card

###
GET localhost:8080/api/v1/content/anime?page=0

###
GET localhost:8080/api/v1/content/anime?page=0&page-to=1

###
GET localhost:8080/api/v1/content/anime

###
GET localhost:8080/api/v1/content/rating/95/my-rating
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg5ODQwOTYsImV4cCI6MTcyOTA3MDQ5Niwic3ViIjoidGVzdCJ9.NJ5s0T-1kd09OhQoCGjPoJ8UUm_TgQtLQkgHaVmZNIStX9Y6wBOoMPtdJXuk7ulE7nsYpZ0Vg9XY0LLgBHNMlQ

###
POST localhost:8080/api/v1/content/rating
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg5ODQwOTYsImV4cCI6MTcyOTA3MDQ5Niwic3ViIjoidGVzdCJ9.NJ5s0T-1kd09OhQoCGjPoJ8UUm_TgQtLQkgHaVmZNIStX9Y6wBOoMPtdJXuk7ulE7nsYpZ0Vg9XY0LLgBHNMlQ


{
    "value": 2,
    "content_id": 95
}


###
POST localhost:8080/api/v1/content/review
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg5ODQwOTYsImV4cCI6MTcyOTA3MDQ5Niwic3ViIjoidGVzdCJ9.NJ5s0T-1kd09OhQoCGjPoJ8UUm_TgQtLQkgHaVmZNIStX9Y6wBOoMPtdJXuk7ulE7nsYpZ0Vg9XY0LLgBHNMlQ


{
        "txt": "govno",
        "content_id": 95,
        "user_id": 5
}

###
GET localhost:8080/api/v1/content/review/95?page=0

###
GET localhost:8080/api/v1/test/test2

//admin jwt
###
GET localhost:8080/api/v1/tags/
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NVUEVSVklTT1IiXSwiaWQiOjcsImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoidGVzdCIsInN1YiI6InRlc3QiLCJpYXQiOjE3MzM1MTkxMzEsImV4cCI6MTczMzY2MzEzMX0.kuJAl2JZHguh4DNsFZ9xoYaMj8lI55U6Zm2_uiCJfS9vgVcjLuqwzrtBbVziT4bYOvNHJybOkLTqn05USIEerwa0fLS-7EZFDWu-lxv8bLmydbZ7FHmJiYG9YBmqFp-j2eON_Dmgo2fEXqW9X-oOj4Jnhr3WZW-KUZ49nhZ7tigA8JONO1j9e1almmvkCumJoEUipiEaoITgYB3UiIgR9laRvJ6ABKppwX9N9FvnkB_rdjYEMVDl7uX_XPj0_vH_Mg0ll46QQN5Ien0AY0LY6inuWrYOo5Agpbj0kjYrKYmsBJzzeFX50K7AVD_yZhRxKZlEnHyAk4Al8xherWolSg
//user jwt
###
GET localhost:8080/api/v1/tags
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJpZCI6NywiZW5hYmxlZCI6dHJ1ZSwidXNlcm5hbWUiOiJ0ZXN0Iiwic3ViIjoidGVzdCIsImlhdCI6MTczMzA3Njg4MywiZXhwIjoxNzMzMjIwODgzfQ.UjJAh6rqlYsitB8_CMSzshZoW67ZEKULNA9xdeuT45CpyPWj-KHDuoK3d2brRyJumV6d3KAzykwfBERRoCVrNx2iFvJceQ8wWcFl4p1sqUUW-XE8PlJPSy-uRCz5CksAnonZP-fGcMniIm92J2j0BIas1svaxDqpoaDhjDnc7dbf7WD59y7AQas0vcokbgKMM5rCGjkjLAiTHWTVJSjlLezYUYj_yyUfhiuuO_dIZfFw6HoUUP7S0cvhRoxi-yO_LbuV-_jUYzEySpKZU4mzCZ5x4piwo9ys6vYkwR7dFJsQNkRGerfPpqc93oqud6bYptASA18WRKrndW29SOWN5w

###
GET localhost:8080/api/v1/tags/content/95
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NVUEVSVklTT1IiXSwiaWQiOjcsImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoidGVzdCIsInN1YiI6InRlc3QiLCJpYXQiOjE3MzM1MTkxMzEsImV4cCI6MTczMzY2MzEzMX0.kuJAl2JZHguh4DNsFZ9xoYaMj8lI55U6Zm2_uiCJfS9vgVcjLuqwzrtBbVziT4bYOvNHJybOkLTqn05USIEerwa0fLS-7EZFDWu-lxv8bLmydbZ7FHmJiYG9YBmqFp-j2eON_Dmgo2fEXqW9X-oOj4Jnhr3WZW-KUZ49nhZ7tigA8JONO1j9e1almmvkCumJoEUipiEaoITgYB3UiIgR9laRvJ6ABKppwX9N9FvnkB_rdjYEMVDl7uX_XPj0_vH_Mg0ll46QQN5Ien0AY0LY6inuWrYOo5Agpbj0kjYrKYmsBJzzeFX50K7AVD_yZhRxKZlEnHyAk4Al8xherWolSg

###
GET localhost:8080/api/v1/tags


###
POST localhost:8084/api/v1/auth/test3
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWQiOjcsImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoidGVzdCIsInN1YiI6InRlc3QiLCJpYXQiOjE3MzMwNzQ0NzQsImV4cCI6MTczMzIxODQ3NH0.Qh9Rl10xudaXIzyEopmLn5ZOG7ojKR8HeuqL7TlwxcldRG2SS1I0pvoefqL7MyUYwaLPoSzWmamtTB2qkyu8xcPCFbgPY_iGWLmAZP4prkVHFFjZn2s2r3GZC_lTyRwNqmNL_VkLlMkWIlYW9e3K-80mtZo3Qv507A32kx6nJwBJI1AXtBnJ8jdKRceKy8BKrJahlGSW9kKaWoNX54O1TMFLBxE5sU38w88l4G7AEO7C4qovM02_qx8gmrcTo1j50oTXHTfqHX0SCbL310Eez8sc3iaLZj8-fSKsULMCJkyr5UP0jF9FevOde5g5ajTRRUH3kSp_zyh-MKUmoawnnA
