spring:
  application:
    name: OmegaPoisk
    page: ${SPRING_PAGE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  servlet:
    context-path: ${API_PREFIX}