spring:
  application:
    name: OmegaPoisk
    page-size: ${SPRING_PAGE_SIZE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
  jackson:
    property-naming-strategy: SNAKE_CASE