@token =eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NVUEVSVklTT1IiXSwiaWQiOjcsImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoidGVzdCIsInN1YiI6InRlc3QiLCJpYXQiOjE3MzQ2MjYxNDQsImV4cCI6MTczNTA1ODE0NH0.wP91dfHoVY1AvIjG509z5oRulU4k7x46cF_2-zkOw1TNL-auH6YcxWVt71aiIqEOnD_MHYoi89b18HyuI1DSXj45rZTc9a4akNPJNl6ZuH7vgf1dafGlUcMuDf8wLcOztpjoH9Fl-Oer8p2kR8PG_x2o7Jj0xkpY1bocmBzsjj9AE9BzHsJmndZEe1sLOtpdkEw2xs3WjJt_t1jhz_YPk10qHoDmgk4xktx85TFkct6pHBx84pPajIUNsyo0Njb7P6SgUTk5p72j--uqC507c6CU4Ovfw2J3taOHgLV8_LbC1uqezX7AEj4OQhsod0dmUjXn90hjczuG3l6aOe4TAw

@content=anime

###
GET localhost:8080/api/v1/content/{{content}}?page=0
Authorization: Bearer {{token}}}

###
GET localhost:8080/api/v1/content/{{content}}/95/card
Authorization: Bearer {{token}}}

###
GET localhost:8080/api/v1/content/{{content}}/card?page=0
Authorization: Bearer {{token}}}

###
POST localhost:8080/api/v1/content/{{content}}
Content-Type: application/json
Authorization: Bearer {{token}}}

{
      "id": 0,
      "title": "title",
      "description": "desc",
      "series_num": 26
}