@token =eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NVUEVSVklTT1IiXSwiaWQiOjcsImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoidGVzdCIsInN1YiI6InRlc3QiLCJpYXQiOjE3MzQ2MjE0MzcsImV4cCI6MTczNTA1MzQzN30.BO0zzvNTACBKmHreJDzMyAVoETWp5xuBbWccLhDsIzZmD4UkGPh2XHhASEr8-HrPkHWCqfCztdfL_YJCrMZSvwN6UlAM_u1NTbj-EaplWyf0mPN0MT-Hy8mv5EOdPjU9ij-MvAQrdg5m0OKuAjKue0ZN96nnI8HsrvbqqH7zfrXGbnN_rLN8chSXSg0PXakAAdwmC_GVAMJBBibJtuLuhYHG_Bm5g1-4DktBO9CGzbeFsiRCNWMb7-aD6Ps3tqjBwxkw-nWk28rQnihXKnYW-bWQG79baicwx-XtudDfwbj7F9bpRR1-b5kLIkz42iwJpahnxDuQlBVn5BGq_uIn5Q


###
GET localhost:8080/api/v1/content/rating/95/avg
Authorization: Bearer {{token}}}

###
POST localhost:8080/api/v1/content/rating
Authorization: Bearer {{token}}}
Content-Type: application/json

{
    "value": 2,
    "content_id": 95,
    "user_id":9
}
###

DELETE localhost:8080/api/v1/content/rating/5
Authorization: Bearer {{token}}}
###
GET localhost:8086/v3/api-docs
###
GET localhost:8086/swagger-ui.html
###
GET localhost:8086/api/v1/content/rating/swagger-ui.html
###
GET localhost:8080/api/v1/content/rating/v3/api-docs
###
GET localhost:8080/gateway
###
GET localhost:8080/api/v1/content/rating/v3/api-docs
