spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: tag-service
          uri: lb://tag-service
          predicates:
            - Path=/api/v1/tags/**
          filters:
            - name: CircuitBreaker
              args:
                name: tagCircuitBreaker
                fallbackUri: forward:/fallback
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback
        - id: studio-service
          uri: lb://studio-service
          predicates:
            - Path=/api/v1/studio/**
          filters:
            - name: CircuitBreaker
              args:
                name: studioCircuitBreaker
                fallbackUri: forward:/fallback
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/content/rating/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingCircuitBreaker
                fallbackUri: forward:/fallback
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/content/review/**
          filters:
            - name: CircuitBreaker
              args:
                name: reviewCircuitBreaker
                fallbackUri: forward:/fallback
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

#todo inctances for all services
resilience4j:
  circuitbreaker:
    configs:
      omega:
        slidingWindowSize: 10
        failureRateThreshold: 52
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 10
    instances:
      tagCircuitBreaker:
        base-config: omega
      authCircuitBreaker:
        base-config: omega
      studioCircuitBreaker:
        base-config: omega
      ratingCircuitBreaker:
        base-config: omega
      reviewCircuitBreaker:
        base-config: omega