spring:
  application:
    name: gateway-server
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    gateway:
      routes:
        - id: tag-service
          uri: lb://tag-service
          predicates:
            - Path=/api/v1/tags/**
server:
  port: 8080

