spring:
  application:
    name: review-service
    page: ${SPRING_PAGE:5}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/omega_db}
    username: ${SPRING_DATASOURCE_USERNAME:omega}
    password: ${SPRING_DATASOURCE_PASSWORD:omega}
    driver-class-name: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: ${KAFKA_URLS:kafka1:9092,kafka2:9093,kafka3:9094}
    topic: notification.review
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      session.timeout.ms: 60000
      enable.auto.commit: true
    properties:
      linger.ms: 10
      retries: 3
server:
  port: 8087

# API prefix
api:
  prefix: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

topics:
  create:
    - name: ${spring.kafka.topic}
      partitions: 2
      replication-factor: 2

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/content/review/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/content/review/swagger-ui.html
    default-url: /api/v1/content/review/v3/api-docs
    disable-swagger-default-url: true