spring:
  application:
    name: studio-service
    page: ${SPRING_PAGE:5}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/omega_db}
    username: ${SPRING_DATASOURCE_USERNAME:omega}
    password: ${SPRING_DATASOURCE_PASSWORD:omega}
    driver-class-name: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8081

# API prefix
api:
  prefix: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/studio/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/studio/swagger-ui.html
    default-url: /api/v1/studio/v3/api-docs
    disable-swagger-default-url: true