spring:
  application:
    name: tag-service
    page: ${SPRING_PAGE:5}
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/omega_db
    username: ${SPRING_DATASOURCE_USERNAME:omega}
    password: ${SPRING_DATASOURCE_PASSWORD:omega}
  data:
    r2dbc:
      repositories:
        enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8083

# API prefix
tag-service:
  api:
    prefix: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/tags/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/tags/swagger-ui.html
    default-url: /api/v1/tags/v3/api-docs
    disable-swagger-default-url: true